default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: snake
  password: 132516
  host: localhost
  port: 5432

development:
  <<: *default
  database: phone_book_dev
  

test:
  <<: *default
  database: phone_book_t
  